# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: ci-audit

# Trigger the workflow when:
on:
  # A push modifies one of the matches files.
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:

  audit:
    # NOTE: This name appears in GitHub's Checks API.
    name: audit
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./runtime
    steps:
      - uses: actions/checkout@v4
      - run: cargo audit
